
// This is an automatically generated file. Please do not edit this file directly.
'use server';
/**
 * @fileOverview An AI agent that dynamically adjusts a study schedule based on skipped days.
 *
 * - adaptiveRePlanning - A function that handles the re-planning process.
 * - AdaptiveRePlanningInput - The input type for the adaptiveRePlanning function.
 * - AdaptiveRePlanningOutput - The return type for the adaptiveRePlanning function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TaskSchema = z.object({
  id: z.string(),
  date: z.string(),
  task: z.string(),
  completed: z.boolean(),
  youtubeSearchQuery: z.string().optional(),
  referenceSearchQuery: z.string().optional(),
  subTasks: z.array(z.any()).optional(),
  quizScore: z.number().optional(),
  quizAttempted: z.boolean().optional(),
  notes: z.string().optional(),
});

const AdaptiveRePlanningInputSchema = z.object({
  tasks: z.array(TaskSchema).describe("The list of all tasks from the original plan, including their completion status."),
  skippedDays: z
    .number()
    .int()
    .min(0)
    .describe('The number of days the user skipped in their study schedule.'),
  remainingDays: z.number().int().min(1).describe("The total duration for the new, revised study plan."),
  subjects: z.string().describe('The subject(s) being studied.'),
  dailyStudyHours: z.number().describe('The number of hours available for studying per day.'),
});

export type AdaptiveRePlanningInput = z.infer<typeof AdaptiveRePlanningInputSchema>;

const AdaptiveRePlanningOutputSchema = z.object({
  revisedSchedule: z
    .string()
    .describe(
      "The revised study schedule, delivered as a JSON string. This string must parse into a JavaScript array of objects. Each object in the array represents a single day's study tasks and must contain: 'date' (string, 'YYYY-MM-DD'), 'task' (string, description of activities), an optional 'youtubeSearchQuery' (string, concise YouTube search query), and an optional 'referenceSearchQuery' (string, concise web search query for reference material). Example: '[{\"date\": \"2024-01-10\", \"task\": \"Catch up on Math: Chapter 2 for 3 hours.\", \"youtubeSearchQuery\": \"math chapter 2 algebra tutorial\", \"referenceSearchQuery\": \"algebra chapter 2 summary\"}]'"
    ),
  summary: z.string().describe('A short summary of the changes made to the schedule, mentioning how uncompleted tasks were redistributed.'),
});

export type AdaptiveRePlanningOutput = z.infer<typeof AdaptiveRePlanningOutputSchema>;

export async function adaptiveRePlanning(input: AdaptiveRePlanningInput): Promise<AdaptiveRePlanningOutput> {
  return adaptiveRePlanningFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adaptiveRePlanningPrompt',
  input: {schema: AdaptiveRePlanningInputSchema},
  output: {schema: AdaptiveRePlanningOutputSchema},
  prompt: `You are an expert study plan optimizer. A user has fallen behind on their study schedule and needs a revised plan. **Your primary goal is to create a new schedule that seamlessly continues from where the user left off, only rescheduling tasks that were not completed.** Do not restart subjects from the beginning.

Here is the user's situation:
- Subjects: {{{subjects}}}
- Daily Study Hours: {{{dailyStudyHours}}}
- New plan duration (remaining days): {{{remainingDays}}}
- Skipped Days: {{{skippedDays}}}

Here is the user's original plan with their progress. Pay close attention to the 'Completed' status for each task:
{{#each tasks}}
- Date: {{this.date}}, Task: "{{this.task}}", Completed: {{this.completed}}
{{/each}}

**Instructions for the revised plan:**
1.  **Identify Uncompleted Work:** Carefully review the list above and gather all tasks where \`Completed\` is \`false\`. These are the only tasks you need to worry about.
2.  **Create a Continuation Plan:** Take the list of uncompleted tasks and distribute them logically across the new \`{{{remainingDays}}}\` day timeframe. Start the new plan with the very next topic the user was supposed to study.
3.  **Do Not Include Completed Tasks:** The revised schedule must not contain any tasks that were marked as \`Completed: true\`. The new plan must feel like a direct continuation.
4.  **Balance the Workload:** Adjust the daily workload to be reasonable for the \`{{{dailyStudyHours}}}\` available. You might need to combine smaller uncompleted tasks or split larger ones across multiple days.
5.  **Format the Output:**
    - The \`revisedSchedule\` must be a valid JSON string that can be parsed into a JavaScript array of objects.
    - Each object in the array represents a day and must have: \`date\` (string, 'YYYY-MM-DD'), \`task\` (string, description), \`youtubeSearchQuery\` (optional string), and \`referenceSearchQuery\` (optional string).
    - Ensure dates start from today and increment correctly.
6.  **Summarize Your Changes:** Provide a short \`summary\` explaining how you've redistributed the remaining work. For example: "I've rescheduled the 8 remaining tasks across your new 5-day plan, starting with the topics you missed."
`,
});

const adaptiveRePlanningFlow = ai.defineFlow(
  {
    name: 'adaptiveRePlanningFlow',
    inputSchema: AdaptiveRePlanningInputSchema,
    outputSchema: AdaptiveRePlanningOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
